'use strict';
const money=n=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
function bill(cost,remaining,rate,room){const deductible=Math.min(cost,remaining,room);const coinsurance=Math.min((cost-deductible)*rate,Math.max(0,room-deductible));return {deductible,coinsurance,patient:deductible+coinsurance,insurer:cost-deductible-coinsurance}}
function annual(p,u){const copays=Math.min(u.primary*p.primary+u.specialist*p.specialist,p.max);const b=bill(u.medical,p.deductible,p.rate/100,p.max-copays);return {...b,copays,care:copays+b.patient,premiums:12*p.premium,total:12*p.premium+copays+b.patient}}
const specs={premium:['Monthly premium ($)',0,1000,10],deductible:['Annual deductible ($)',0,10000,100],max:['Annual out-of-pocket maximum ($)',0,15000,100],primary:['Primary care copay ($ per visit)',0,200,5],specialist:['Specialist copay ($ per visit)',0,300,5],rate:['Patient coinsurance (%)',0,100,1]};
function control(id,label,min,max,step,value,container){const d=document.createElement('div');d.className='control';const l=document.createElement('label');l.htmlFor=id;l.textContent=label;const pair=document.createElement('div');pair.className='pair';const n=document.createElement('input');n.type='number';n.id=id;n.min=min;n.max=max;n.step=step;n.value=value;const r=document.createElement('input');r.type='range';r.min=min;r.max=max;r.step=step;r.value=value;r.setAttribute('aria-label',label+' slider');pair.append(r,n);d.append(l,pair);container.append(d);r.addEventListener('input',()=>{n.value=r.value;render()});n.addEventListener('input',()=>{if(n.validity.valid&&n.value!=='')r.value=n.value;render()})}
const defaults=[{premium:200,deductible:4000,max:8000,primary:40,specialist:80,rate:30},{premium:400,deductible:1000,max:4000,primary:20,specialist:40,rate:20}];
defaults.forEach((p,i)=>Object.entries(specs).forEach(([k,s])=>control('p'+i+k,...s,p[k],document.getElementById('plan'+i))));
control('uprimary','Primary care visits this year',0,30,1,3,document.getElementById('use'));control('uspecialist','Specialist visits this year',0,30,1,2,document.getElementById('use'));control('umedical','Other covered medical expenses: total allowed amount ($)',0,100000,100,5000,document.getElementById('use'));
[['bcost','This bill: allowed amount ($)',0,100000,100,5000],['bdeductible','Annual deductible ($)',0,10000,100,2000],['bpaid','Deductible already paid ($)',0,10000,100,500],['bmax','Annual out-of-pocket maximum ($)',0,15000,100,6000],['bspent','Eligible out-of-pocket spending already paid ($)',0,15000,100,500],['brate','Patient coinsurance (%)',0,100,1,20]].forEach(s=>control(...s,document.getElementById('bill-controls')));
const value=id=>Number(document.getElementById(id).value);
function valid(container){return [...container.querySelectorAll('input[type=number]')].every(n=>n.value!==''&&n.validity.valid)}
function render(){renderAnnual();renderBill()}
function renderAnnual(){const out=document.getElementById('annual-result');const p=defaults.map((_,i)=>Object.fromEntries(Object.keys(specs).map(k=>[k,value('p'+i+k)])));if(!valid(document.getElementById('annual'))||p.some(x=>x.deductible>x.max)){out.innerHTML='<p class="error" role="status">Enter values within the displayed ranges. Each deductible must be no greater than its out-of-pocket maximum.</p>';return}
const u={primary:value('uprimary'),specialist:value('uspecialist'),medical:value('umedical')};const a=p.map(x=>annual(x,u));const diff=a[0].total-a[1].total;const peak=Math.max(...a.map(x=>x.total),1);
out.innerHTML='<h2>Annual cost comparison</h2><p class="total">'+(Math.abs(diff)<.005?'Same total annual spending': 'Plan '+(diff>0?'B':'A')+' costs '+money(Math.abs(diff))+' less')+'</p><p>For this healthcare-use scenario. Lower modeled cost does not automatically mean a better plan.</p>'+a.map((x,i)=>'<p><strong>Plan '+(i?'B':'A')+': '+money(x.total)+'</strong></p><div class="bar" aria-hidden="true"><span class="premium" style="width:'+100*x.premiums/peak+'%"></span><span class="care" style="width:'+100*x.care/peak+'%"></span></div>').join('')+'<p class="muted"><span class="key premium"></span>Premiums <span class="key care"></span>Covered-care spending. Exact values follow.</p><table><caption>Same healthcare use, different plan rules</caption><thead><tr><th scope="col">Annual spending</th><th scope="col">Plan A</th><th scope="col">Plan B</th></tr></thead><tbody>'+[['Premiums',...a.map(x=>x.premiums)],['Copays paid',...a.map(x=>x.copays)],['Deductible paid',...a.map(x=>x.deductible)],['Coinsurance paid',...a.map(x=>x.coinsurance)],['Covered-care spending',...a.map(x=>x.care)],['Total annual spending',...a.map(x=>x.total)],['Premiums + maximum covered-care spending',...p.map(x=>12*x.premium+x.max)]].map(row=>'<tr><th scope="row">'+row[0]+'</th><td>'+money(row[1])+'</td><td>'+money(row[2])+'</td></tr>').join('')+'</tbody></table><details><summary>Follow the annual calculation</summary>'+a.map((x,i)=>'<p><strong>Plan '+(i?'B':'A')+'</strong>: '+u.primary+' primary visits × '+money(p[i].primary)+' + '+u.specialist+' specialist visits × '+money(p[i].specialist)+' = '+money(u.primary*p[i].primary+u.specialist*p[i].specialist)+' in scheduled copays. Actual copays paid: '+money(x.copays)+', capped by the out-of-pocket limit.</p><p>From '+money(u.medical)+' in other allowed expenses, pay '+money(x.deductible)+' toward the deductible, then '+p[i].rate+'% of the remaining expenses, stopping at the out-of-pocket limit. Coinsurance actually paid: '+money(x.coinsurance)+'.</p><p>'+money(x.premiums)+' premiums + '+money(x.care)+' covered-care spending = '+money(x.total)+'.</p>').join('')+'</details><p><strong>Explore:</strong> An extra '+money(p[1].premium-p[0].premium)+' per month for Plan B means '+money(12*(p[1].premium-p[0].premium))+' in annual premiums. Change medical expenses to see whether savings on care offset that difference.</p><p><strong>Consider:</strong> Which plan has a more manageable monthly payment? Which exposes someone to a larger unexpected bill? What information about providers and coverage is still missing?</p>'}
function renderBill(){const out=document.getElementById('bill-result');const cost=value('bcost'),d=value('bdeductible'),paid=value('bpaid'),max=value('bmax'),spent=value('bspent'),rate=value('brate');if(!valid(document.getElementById('single'))||d>max||paid>d||spent>max||spent<paid){out.innerHTML='<p class="error" role="status">Check the values: deductible cannot exceed the maximum; deductible paid cannot exceed the deductible; eligible spending must include deductible paid and cannot exceed the maximum.</p>';return}
const remaining=d-paid,room=max-spent,b=bill(cost,remaining,rate/100,room);
out.innerHTML='<h2>Who pays this bill?</h2><p class="total">You pay '+money(b.patient)+'</p><table><caption>Payment breakdown for this covered, in-network bill</caption><tbody>'+[['Allowed amount',cost],['Deductible remaining before this bill',remaining],['Room before out-of-pocket maximum',room],['You pay toward deductible',b.deductible],['You pay in coinsurance',b.coinsurance],['Insurance pays',b.insurer],['Deductible remaining after this bill',remaining-b.deductible],['Eligible spending after this bill',spent+b.patient]].map(x=>'<tr><th scope="row">'+x[0]+'</th><td>'+money(x[1])+'</td></tr>').join('')+'</tbody></table><p>First, '+money(b.deductible)+' of this bill goes toward your remaining deductible. Next, your '+rate+'% share applies to the remaining '+money(cost-b.deductible)+'. Your payment stops when eligible spending reaches '+money(max)+'.</p><p class="muted">Premiums are separate and are not included in this bill breakdown.</p>'}
document.querySelectorAll('[data-panel]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-panel]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));['single','annual'].forEach(id=>document.getElementById(id).hidden=id!==b.dataset.panel)}));
document.querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>{const u={few:[1,0,0],regular:[8,6,5000],major:[3,2,50000]}[b.dataset.scenario];['primary','specialist','medical'].forEach((k,i)=>{const n=document.getElementById('u'+k);n.value=u[i];n.previousElementSibling.value=u[i]});render();document.getElementById('scenario-status').textContent=b.textContent+' loaded.'}));
document.getElementById('reset').addEventListener('click',()=>{defaults.forEach((p,i)=>Object.keys(specs).forEach(k=>{const n=document.getElementById('p'+i+k);n.value=p[k];n.previousElementSibling.value=p[k]}));render();document.getElementById('scenario-status').textContent='Example plan settings restored. Healthcare use remains as entered.'});
render();
