'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
const plans=[{premium:150,d:3000,max:11500,pc:30,sp:40,r:.2},{premium:500,d:1000,max:5750,pc:20,sp:30,r:.15}];
const people={A:{name:'Person A: rarely uses care',pc:1,sp:0,cost:0,alt:5000,story:'Rarely visits a doctor and has no ongoing medical conditions.'},B:{name:'Person B: regular care',pc:6,sp:3,cost:5000,alt:20000,story:'Has diabetes and high blood pressure. This fictional year includes regular visits and additional testing.'},C:{name:'Person C: planned surgery',pc:2,sp:6,cost:40000,alt:70000,story:'Plans orthopedic surgery, hospitalization, and physical therapy. Other expenses combine these services.'},D:{name:'Person D: concerned about an emergency',pc:2,sp:0,cost:0,alt:50000,story:'Usually needs little care, but wants to consider an unexpected major medical expense.'}};
function bill(cost,d,r,max){const ded=Math.min(cost,d,max),co=Math.min((cost-ded)*r,max-ded);return {ded,co,total:ded+co,insurer:cost-ded-co}}
function annual(p,u,cost){const copay=Math.min(u.pc*p.pc+u.sp*p.sp,p.max),b=bill(cost,p.d,p.r,p.max-copay);return {premium:p.premium*12,copay,ded:b.ded,co:b.co,care:copay+b.total,total:p.premium*12+copay+b.total}}
let state={version:1,done:0,page:0,fields:{},ranBill:false,ranPeople:false};
try{const saved=JSON.parse(localStorage.getItem('hes-insurance-assignment-v1'));if(saved&&saved.version===1&&saved.fields&&typeof saved.fields==='object'&&Number.isInteger(saved.done)&&saved.done>=0&&saved.done<=4){state={...state,...saved};state.page=Math.min(state.page,state.done,4)}}catch{}
function save(){try{localStorage.setItem('hes-insurance-assignment-v1',JSON.stringify(state));$('save-status').textContent='Saved on this browser. Download a work backup before changing devices.'}catch{$('save-status').textContent='Browser saving is unavailable. Download a work backup before leaving.'}}
function field(id,label,type='text',options=''){return '<label for="'+id+'">'+label+'</label>'+(type==='textarea'?'<textarea id="'+id+'" data-field rows="3"></textarea>':type==='select'?'<select id="'+id+'" data-field>'+options+'</select>':'<input id="'+id+'" data-field type="'+type+'" '+(type==='number'?'min="0" max="5000" step="0.01"':'')+'>')}
const planTable='<table><caption>Fictional 2027 individual plans</caption><thead><tr><th scope="col">Plan detail</th><th scope="col">Plan A</th><th scope="col">Plan B</th></tr></thead><tbody>'+[['Monthly premium','$150','$500'],['Annual premiums','$1,800','$6,000'],['Annual deductible','$3,000','$1,000'],['Out-of-pocket maximum','$11,500','$5,750'],['Primary care copay','$30','$20'],['Specialist copay','$40','$30'],['Patient coinsurance','20%','15%']].map(x=>'<tr>'+x.map((v,i)=>i?'<td>'+v+'</td>':'<th scope="row">'+v+'</th>').join('')+'</tr>').join('')+'</tbody></table>';
const opts='<option value="">Choose a plan</option><option value="A">Plan A</option><option value="B">Plan B</option>';
const sections=[
'<h2 tabindex="-1">1. Predict one bill</h2><p>Make an estimate before seeing the calculation. Your prediction does not have to be correct.</p>'+field('name','Name for your report (use the name required by your instructor)')+'<article class="bill"><h3>Fictional medical statement</h3><p>Service: covered, in-network outpatient procedure</p><p>Provider charge: $6,500<br><strong>Allowed amount used by insurance: $5,000</strong></p><p>No copay. Deductible: $1,000; already paid: $0. Patient coinsurance: 15%. Out-of-pocket maximum: $10,000; eligible spending already paid: $0.</p></article><p class="hint">Allowed amount means the cost insurance uses to calculate this bill. The provider charge is not used here.</p>'+field('prediction','How much do you predict the patient will pay ($)?','number')+field('predictWhy','Briefly explain your estimate.','textarea')+'<p>Your original prediction will be saved when you continue.</p>',
'<h2 tabindex="-1">2. Follow the bill</h2><p>Use the same $5,000 allowed amount under two sets of plan rules.</p><table><caption>Preset bill scenarios</caption><thead><tr><th scope="col">Detail</th><th scope="col">Scenario 1</th><th scope="col">Scenario 2</th></tr></thead><tbody>'+[['Deductible','$1,000','$700'],['Deductible already paid','$0','$200'],['Eligible spending already paid','$0','$200'],['Out-of-pocket maximum','$10,000','$8,000'],['Patient coinsurance','15%','20%']].map(x=>'<tr><th scope="row">'+x[0]+'</th><td>'+x[1]+'</td><td>'+x[2]+'</td></tr>').join('')+'</tbody></table><p class="hint">In Scenario 2, the $200 already spent consists entirely of deductible payments.</p><button id="run-bill" type="button">Calculate both bills</button><div id="bill-results"></div>'+field('billWhy','Compare your prediction with the results. Explain how the deductible and coinsurance affected payment, and whether either out-of-pocket maximum affected this bill. A few sentences are enough.','textarea'),
'<h2 tabindex="-1">3. Make an initial plan choice</h2><p>If you did not know how much care you would need next year, which plan would you choose? There is no single correct choice.</p>'+planTable+'<p class="hint">Premiums are paid even without care. They do not count toward the deductible or out-of-pocket maximum.</p>'+field('initial','Your initial choice','select',opts)+field('initialWhy','Why would you choose this plan?','textarea')+'<p>Your initial choice will be preserved. You can reconsider it in the final section.</p>',
'<h2 tabindex="-1">4. Investigate two people</h2><p>Choose one lower-use person and one higher-use person. Calculate the supplied expected year and a higher-expense year. You do not need to guess medical prices.</p>'+field('low','Lower-use person','select','<option value="">Choose a person</option><option value="A">Person A: rarely uses care</option><option value="D">Person D: concerned about an emergency</option>')+field('high','Higher-use person','select','<option value="">Choose a person</option><option value="B">Person B: regular care</option><option value="C">Person C: planned surgery</option>')+'<div id="person-details"></div><button id="run-people" type="button">Calculate both people and their alternative years</button><div id="people-results"></div><p class="hint">For each person, recommend a plan. Use dollar amounts for annual premiums and expected total spending. Explain what changes if care costs more or less, and name one thing the model cannot tell you. A short paragraph is enough.</p>'+field('lowWhy','Recommendation for your lower-use person','textarea')+field('highWhy','Recommendation for your higher-use person','textarea')+field('finalWhy','Would you keep or change your initial choice? Explain using one result.','textarea'),
'<h2 tabindex="-1">5. Review and download</h2><p>Review your evidence below, then download the PDF to submit in Canvas. Completion checks only confirm that responses are present; your instructor evaluates the reasoning.</p><button id="pdf" type="button">Download assignment PDF</button><p id="pdf-status" role="status"></p><div id="report"></div><details><summary>Optional: explore your own plan privately</summary><p>Open the original explorer for personal practice. Its inputs are separate and never included in this assignment PDF. Do not upload bills or enter identifying medical information. Real plans may use different rules.</p><a href="/health-insurance/" target="_blank" rel="noopener">Open the practice explorer in a new tab</a></details>'
];
function data(id){return String(state.fields[id]??'')}
function comparison(u,cost){const a=plans.map(p=>annual(p,u,cost));return '<table><caption>Total allowed other expenses: '+money(cost)+'</caption><thead><tr><th scope="col">Annual spending</th><th scope="col">Plan A</th><th scope="col">Plan B</th></tr></thead><tbody>'+[['Premiums','premium'],['Copays','copay'],['Deductible paid','ded'],['Coinsurance paid','co'],['Covered-care spending','care'],['Total: premiums + care','total']].map(([l,k])=>'<tr><th scope="row">'+l+'</th>'+a.map(x=>'<td>'+money(x[k])+'</td>').join('')+'</tr>').join('')+'</tbody></table><p><strong>'+ (Math.abs(a[0].total-a[1].total)<.01?'Same total spending.':'Plan '+(a[0].total<a[1].total?'A':'B')+' costs '+money(Math.abs(a[0].total-a[1].total))+' less in this year.')+'</strong></p>'}
function billResults(){return '<div class="grid">'+[[1000,.15,10000],[500,.2,7800]].map(([d,r,m],i)=>{const b=bill(5000,d,r,m);return '<article class="card"><h3>Scenario '+(i+1)+': you pay '+money(b.total)+'</h3><p>Deductible payment: '+money(b.ded)+'<br>Coinsurance payment: '+money(b.co)+'<br>Insurance pays: '+money(b.insurer)+'</p><p>You pay the first '+money(d)+' toward the remaining deductible, then '+r*100+'% of '+money(5000-d)+'. The maximum is not reached.</p></article>'}).join('')+'</div>'}
function peopleResults(){return ['low','high'].map(k=>{const u=people[data(k)];return u?'<article><h3>'+u.name+'</h3><p>'+u.story+' Primary care visits: '+u.pc+'; specialist visits: '+u.sp+'.</p><h4>Expected year</h4>'+comparison(u,u.cost)+'<h4>Higher-expense year: same visits</h4>'+comparison(u,u.alt)+'</article>':''}).join('')}
function reportHTML(){return '<h3>'+esc(data('name'))+'</h3><p>HES100 - Health Insurance Investigation - fictional 2027 plans</p><h3>1. Original prediction</h3><p>Allowed bill: $5,000. Predicted patient payment: '+money(Number(data('prediction')))+'</p><p>'+esc(data('predictWhy'))+'</p><h3>2. Bill evidence</h3>'+billResults()+'<p>'+esc(data('billWhy'))+'</p><h3>3. Initial plan choice</h3>'+planTable+'<p>Plan '+esc(data('initial'))+': '+esc(data('initialWhy'))+'</p><h3>4. Scenario evidence and recommendations</h3>'+peopleResults()+'<h4>Lower-use recommendation</h4><p>'+esc(data('lowWhy'))+'</p><h4>Higher-use recommendation</h4><p>'+esc(data('highWhy'))+'</p><h3>5. Reconsidered choice</h3><p>'+esc(data('finalWhy'))+'</p><p>Model: copays before deductible; other costs use deductible then coinsurance; covered in-network care only. Premiums remain separate. Office visits are processed first. All medical costs are illustrative allowed amounts, not real prices. Networks, exclusions, drug benefits, family rules and subsidies are not modeled.</p><p>Sources: healthcare.gov/glossary/deductible/; healthcare.gov/glossary/co-insurance/; healthcare.gov/glossary/out-of-pocket-maximum-limit/</p>'}
function draw(){document.querySelectorAll('[data-step]').forEach((b,i)=>{b.disabled=i>state.done;b.setAttribute('aria-current',i===state.page?'step':'false');b.textContent=(i+1)+'. '+['Predict','Follow bill','Choose plan','Investigate','PDF'][i]+(i>state.done?' (locked)':'')});
$('content').innerHTML=sections[state.page];$('progress').textContent='Section '+(state.page+1)+' of 5. '+state.done+' of 4 work sections complete.';
document.querySelectorAll('[data-field]').forEach(e=>{e.value=data(e.id);if((state.page===0&&state.done>0)||(state.page===2&&state.done>2))e.disabled=true;e.addEventListener('input',()=>{state.fields[e.id]=e.value;if(state.page===1||state.page===3){state.done=Math.min(state.done,state.page);document.querySelectorAll('[data-step]').forEach((b,i)=>{b.disabled=i>state.done})}if(e.id==='low'||e.id==='high'){state.ranPeople=false;state.fields.lowWhy='';state.fields.highWhy='';state.fields.finalWhy='';state.done=Math.min(state.done,3);draw()}save()})});
if(state.page===1){if(state.ranBill)$('bill-results').innerHTML=billResults();$('run-bill').onclick=()=>{state.ranBill=true;$('bill-results').innerHTML=billResults();save()}}
if(state.page===3){$('person-details').innerHTML=['low','high'].map(k=>{const u=people[data(k)];return u?'<p><strong>'+u.name+'</strong>: '+u.story+' '+u.pc+' primary visits, '+u.sp+' specialist visits, '+money(u.cost)+' other allowed expenses; higher-expense test: '+money(u.alt)+'.</p>':''}).join('');if(state.ranPeople)$('people-results').innerHTML=peopleResults();$('run-people').onclick=()=>{if(!data('low')||!data('high')){error('Choose both people first.');return}state.ranPeople=true;$('people-results').innerHTML=peopleResults();save()}}
if(state.page===4){$('report').innerHTML=reportHTML();$('pdf').onclick=downloadPDF}
$('back').hidden=state.page===0;$('next').hidden=state.page===4;$('error').textContent='';}
function error(message){$('error').textContent=message;$('error').focus()}
function check(page){const req=[['name','prediction','predictWhy'],['billWhy'],['initial','initialWhy'],['low','high','lowWhy','highWhy','finalWhy']][page];for(const id of req){if(!data(id).trim()){error('Complete: '+document.querySelector('label[for="'+id+'"]').textContent);$(id).focus();return false}}
if(page===0&&(!Number.isFinite(Number(data('prediction')))||Number(data('prediction'))<0||Number(data('prediction'))>5000)){error('Enter a prediction from $0 to $5,000.');return false}
if(page===1&&!state.ranBill){error('Calculate both bills before continuing.');return false}if(page===3&&!state.ranPeople){error('Calculate both people before continuing.');return false}return true}
function go(n){if(n>state.done)return;state.page=n;draw();$('content').querySelector('h2').focus();save()}
$('next').onclick=()=>{if(check(state.page)){state.done=Math.max(state.done,state.page+1);go(state.page+1)}};
$('back').onclick=()=>go(state.page-1);document.querySelectorAll('[data-step]').forEach((b,i)=>b.onclick=()=>go(i));
$('backup').onclick=()=>download(JSON.stringify(state,null,2),'health-insurance-work.json','application/json');
$('restore').onchange=async e=>{try{const v=JSON.parse(await e.target.files[0].text());const allowed=['name','prediction','predictWhy','billWhy','initial','initialWhy','low','high','lowWhy','highWhy','finalWhy'];if(v.version!==1||!Number.isInteger(v.done)||v.done<0||v.done>4||!v.fields||allowed.some(k=>v.fields[k]!=null&&(typeof v.fields[k]!=='string'||v.fields[k].length>20000)))throw Error();state={version:1,done:v.done,page:Math.min(v.done,4),fields:Object.fromEntries(allowed.map(k=>[k,v.fields[k]||''])),ranBill:!!v.ranBill,ranPeople:!!v.ranPeople};save();draw()}catch{error('This file is not a valid assignment backup. Your current work was kept.')}};
function download(body,name,type){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([body],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function downloadPDF(){if(!window.jspdf){$('pdf-status').textContent='PDF library did not load. Reload and try again; your saved work is kept.';return}const doc=new window.jspdf.jsPDF({unit:'pt',format:'letter'});let y=60;const height=792,margin=44;
function newPage(){doc.addPage();y=60}
function text(s,bold=false){doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(bold?12:10);const lines=doc.splitTextToSize(String(s).normalize('NFKD').replace(/[\u0300-\u036f]/g,''),524);for(const line of lines){if(y>height-65)newPage();doc.text(line,margin,y);y+=14}y+=7}
function row(label,a,b){if(y>height-65)newPage();doc.setDrawColor(210);doc.line(margin,y+5,568,y+5);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text(label,margin,y);doc.text(a,365,y);if(b!=null)doc.text(b,465,y);y+=22}
text('HEALTH INSURANCE INVESTIGATION',true);text(data('name')+' | HES100 | Fictional 2027 plans');
text('1. ORIGINAL PREDICTION',true);text('Allowed bill: $5,000 | Predicted payment: '+money(Number(data('prediction'))));text(data('predictWhy'));
text('2. FOLLOW ONE BILL',true);row('Payment breakdown','Scenario 1','Scenario 2');row('Deductible / already paid','$1,000 / $0','$700 / $200');row('Maximum / eligible spending paid','$10,000 / $0','$8,000 / $200');row('Patient coinsurance','15%','20%');row('Deductible payment','$1,000','$500');row('Coinsurance payment','$600','$900');row('Patient total','$1,600','$1,400');row('Insurance pays','$3,400','$3,600');text(data('billWhy'));
newPage();text('3. INITIAL PLAN CHOICE',true);row('Plan detail','Plan A','Plan B');[['Monthly premium',150,500],['Annual premiums',1800,6000],['Deductible',3000,1000],['Out-of-pocket maximum',11500,5750],['Primary copay',30,20],['Specialist copay',40,30]].forEach(x=>row(x[0],money(x[1]),money(x[2])));row('Patient coinsurance','20%','15%');text('Initial choice: Plan '+data('initial'));text(data('initialWhy'));
['low','high'].forEach(k=>{const u=people[data(k)];newPage();text('4. '+u.name.toUpperCase(),true);text(u.story);text(u.pc+' primary visits; '+u.sp+' specialist visits.');[u.cost,u.alt].forEach((cost,i)=>{text((i?'Higher-expense':'Expected')+' year: '+money(cost)+' other allowed expenses',true);const a=plans.map(p=>annual(p,u,cost));row('Annual spending','Plan A','Plan B');[['Premiums','premium'],['Copays','copay'],['Deductible paid','ded'],['Coinsurance paid','co'],['Covered-care spending','care'],['Total premiums + care','total']].forEach(([l,key])=>row(l,money(a[0][key]),money(a[1][key])))});text('Recommendation',true);text(data(k+'Why'))});
text('5. RECONSIDERED CHOICE',true);text(data('finalWhy'));text('MODEL AND SOURCES',true);text('Fictional allowed costs, not market prices. Covered in-network care only. Visit copays apply before deductible and count toward the maximum, but not the deductible. Visits are processed first. Other expenses use deductible then coinsurance. Premiums are separate. Networks, exclusions, drug benefits, subsidies and family rules are not modeled.');text('HealthCare.gov: healthcare.gov/glossary/deductible/; healthcare.gov/glossary/co-insurance/; healthcare.gov/glossary/out-of-pocket-maximum-limit/');
const count=doc.getNumberOfPages();for(let i=1;i<=count;i++){doc.setPage(i);doc.setFontSize(9);doc.setTextColor(80);doc.text('HES100 | Health insurance evidence',44,30);doc.text(i+' / '+count,520,765)}doc.save('health-insurance-assignment.pdf');$('pdf-status').textContent='PDF downloaded. Open it to check your responses, then submit it in Canvas.'}
draw();save();
