'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
const KEY='hes-insurance-assignment-v2';
const plans=[{premium:150,d:3000,max:11500,pc:30,sp:40,r:.2},{premium:500,d:1000,max:5750,pc:20,sp:30,r:.15}];
const people={A:{name:'Person A: rarely uses care',pc:1,sp:0,cost:0,story:'Rarely visits a doctor and has no ongoing medical conditions.'},B:{name:'Person B: regular care',pc:6,sp:3,cost:5000,story:'Has diabetes and high blood pressure. This fictional year includes six primary care visits, three specialist visits, and additional testing.'},C:{name:'Person C: planned surgery',pc:2,sp:6,cost:40000,story:'Plans orthopedic surgery, hospitalization, and physical therapy. Other medical expenses combine these services.'},D:{name:'Person D: concerned about an emergency',pc:2,sp:0,cost:0,story:'Usually needs little care, but is concerned about an unexpected major medical expense.'}};
const baseline={d:1000,paid:0,rate:15,max:10000};
function bill(s){const ded=Math.min(5000,Math.max(0,s.d-s.paid)),co=Math.min((5000-ded)*s.rate/100,Math.max(0,s.max-s.paid-ded));return {ded,co,total:ded+co,insurer:5000-ded-co}}
function annual(p,u,cost){const copay=Math.min(u.pc*p.pc+u.sp*p.sp,p.max),ded=Math.min(cost,p.d,p.max-copay),co=Math.min((cost-ded)*p.r,Math.max(0,p.max-copay-ded));return {premium:p.premium*12,copay,ded,co,care:copay+ded+co,total:p.premium*12+copay+ded+co}}
const fresh=()=>({version:2,page:0,done:0,fields:{},billRun:false,attempts:{more:[],less:[]},ready:{more:false,less:false},labs:{low:{run:false,tests:[]},high:{run:false,tests:[]}}});
let state=fresh();
function valid(v){return v&&v.version===2&&Number.isInteger(v.done)&&v.done>=0&&v.done<=7&&v.fields&&typeof v.fields==='object'&&!Array.isArray(v.fields)&&Object.values(v.fields).every(x=>typeof x==='string'&&x.length<=20000)&&v.ready&&v.attempts&&['more','less'].every(k=>Array.isArray(v.attempts[k])&&v.attempts[k].length<=200&&v.attempts[k].every(t=>['d','paid','rate'].includes(t.factor)&&Number.isFinite(t.value)&&t.value>=0&&t.value<=10000))&&v.labs&&['low','high'].every(k=>v.labs[k]&&Array.isArray(v.labs[k].tests)&&v.labs[k].tests.length<=200&&v.labs[k].tests.every(t=>Number.isFinite(t.cost)&&t.cost>=0&&t.cost<=100000))}
try{const v=JSON.parse(localStorage.getItem(KEY));if(valid(v)){state=v;state.page=Math.max(0,Math.min(Number(v.page)||0,v.done,7))}}catch{}
const data=id=>state.fields[id]??'';
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('save-status').textContent='Saved on this browser. Download a work backup before changing devices.'}catch{$('save-status').textContent='Browser saving is unavailable. Download a work backup before leaving.'}}
function field(id,label,type='textarea',options=''){return '<label for="'+id+'">'+label+'</label>'+(type==='select'?'<select data-field id="'+id+'">'+options+'</select>':type==='textarea'?'<textarea data-field id="'+id+'" rows="3"></textarea>':'<input data-field id="'+id+'" type="'+type+'" '+(type==='number'?'min="0" max="5000" step="1"':'')+'>')}
const opts='<option value="">Choose a plan</option><option value="A">Plan A</option><option value="B">Plan B</option>';
const planRows=[['Monthly premium',150,500],['Annual premiums',1800,6000],['Deductible',3000,1000],['Out-of-pocket maximum',11500,5750],['Primary care copay',30,20],['Specialist copay',40,30]];
const planTable='<table><caption>Fictional 2027 individual plans</caption><thead><tr><th scope="col">Plan detail</th><th scope="col">Plan A</th><th scope="col">Plan B</th></tr></thead><tbody>'+planRows.map(x=>'<tr><th scope="row">'+x[0]+'</th><td>'+money(x[1])+'</td><td>'+money(x[2])+'</td></tr>').join('')+'<tr><th scope="row">Patient coinsurance</th><td>20%</td><td>15%</td></tr></tbody></table>';
function slider(id,label,min,max,step,value,unit='$'){return '<label for="'+id+'">'+label+'</label><div class="pair"><input id="'+id+'" type="range" min="'+min+'" max="'+max+'" step="'+step+'" value="'+value+'"><label class="sr-only" for="'+id+'-number">'+label+' (exact value)</label><input id="'+id+'-number" type="number" min="'+min+'" max="'+max+'" step="'+step+'" value="'+value+'"></div><p id="'+id+'-value" class="muted">'+(unit==='$'?money(value):value+'%')+'</p>'}
function bindSlider(id,callback){const a=$(id),b=$(id+'-number');function update(e){const n=Number(e.target.value);if(e.target.value===''||!Number.isFinite(n)||n<Number(a.min)||n>Number(a.max)){b.setCustomValidity('Enter a value between '+a.min+' and '+a.max+'.');callback(null);return}b.setCustomValidity('');a.value=n;b.value=n;$(id+'-value').textContent=id.includes('rate')?n+'%':money(n);callback(n)}a.oninput=update;b.oninput=update}
function billSummary(s){const b=bill(s);return '<p class="total">Patient pays '+money(b.total)+'</p><p>Deductible payment: '+money(b.ded)+'<br>Coinsurance payment: '+money(b.co)+'<br>Insurance pays: '+money(b.insurer)+'</p><p>You pay the remaining deductible first, then your percentage of the remaining bill, up to the eligible spending limit.</p>'}
function comparison(u,cost){const a=plans.map(p=>annual(p,u,cost));return '<table><caption>Other medical expenses: '+money(cost)+'</caption><thead><tr><th scope="col">Annual spending</th><th scope="col">Plan A</th><th scope="col">Plan B</th></tr></thead><tbody>'+[['Premiums','premium'],['Covered-care spending','care'],['Total: premiums + care','total']].map(([l,k])=>'<tr><th scope="row">'+l+'</th>'+a.map(x=>'<td>'+money(x[k])+'</td>').join('')+'</tr>').join('')+'</tbody></table><p><strong>'+winner(u,cost)+'</strong></p>'}
function winner(u,cost){const a=plans.map(p=>annual(p,u,cost));return Math.abs(a[0].total-a[1].total)<.01?'Both plans have the same total.':'Plan '+(a[0].total<a[1].total?'A':'B')+' costs '+money(Math.abs(a[0].total-a[1].total))+' less overall.'}
const factors={d:{label:'Annual deductible',min:0,max:10000,step:100},paid:{label:'Deductible already paid',min:0,max:1000,step:50},rate:{label:'Patient coinsurance',min:0,max:100,step:1}};
function experimentHTML(k){const t=state.attempts[k].at(-1),factor=data(k+'Factor')||'d',f=factors[factor];return '<article class="card"><h3>Make the patient pay '+k+'</h3><p>Start from the original plan. Change one insurance setting; the $5,000 bill stays fixed.</p>'+field(k+'Predict','Which setting will you change, and why do you expect the patient to pay '+k+'?')+field(k+'Factor','Setting to change','select',Object.entries(factors).map(([key,x])=>'<option value="'+key+'">'+x.label+'</option>').join(''))+'<div id="'+k+'-slider">'+slider(k+'-setting',f.label,f.min,f.max,f.step,Number(data(k+'Value')||baseline[factor]),factor==='rate'?'%':'$')+'</div><button id="test-'+k+'" type="button">Test and save this change</button><div id="'+k+'-result" role="status">'+(t&&state.ready[k]?attemptHTML(t):'Test and save your current setting.')+'</div>'+field(k+'Why','Explain why this setting changed the patient’s payment. Use deductible or coinsurance as appropriate.')+'</article>'}
function settingsFor(t){return {...baseline,[t.factor]:t.value}}
function attemptHTML(t){const b=bill(settingsFor(t)),diff=b.total-bill(baseline).total;return '<table><caption>Saved change: '+factors[t.factor].label+'</caption><thead><tr><th scope="col">Evidence</th><th scope="col">Original</th><th scope="col">Changed</th></tr></thead><tbody><tr><th scope="row">Setting</th><td>'+baseline[t.factor]+(t.factor==='rate'?'%':' dollars')+'</td><td>'+t.value+(t.factor==='rate'?'%':' dollars')+'</td></tr><tr><th scope="row">Patient payment</th><td>'+money(bill(baseline).total)+'</td><td>'+money(b.total)+'</td></tr></tbody></table><p>Difference: '+money(diff)+'. '+(Math.abs(diff)<.01?'Payment stayed the same. Try another value or setting.':'')+'</p>'}
function personIntro(k){const u=people[data(k)];return '<h3>'+u.name+'</h3><p>'+u.story+'</p><p>Expected year: '+u.pc+' primary care visits, '+u.sp+' specialist visits, and '+money(u.cost)+' other medical expenses.</p>'}
function labHTML(k){const u=people[data(k)],lab=state.labs[k];return '<h2 tabindex="-1">'+(k==='low'?'5':'6')+'. Explore your '+(k==='low'?'lower':'higher')+'-use person</h2>'+personIntro(k)+'<p>Your prediction: Plan '+esc(data(k+'Prediction'))+'. '+esc(data(k+'PredictWhy'))+'</p><button id="run-lab" type="button">Calculate the expected year</button><div id="baseline-result">'+(lab.run?comparison(u,u.cost):'')+'</div><div id="lab-experiment" '+(!lab.run?'hidden':'')+'><h3>Try a different year</h3><p>Change other medical expenses. Visits and plan rules stay fixed. Investigate whether the other plan can become less expensive overall. You do not have to find a reversal.</p>'+field(k+'TestPredict','Before testing: what do you expect this change to do to the comparison?')+slider('medical-cost','Other medical expenses for the year',0,100000,100,Number(data(k+'Cost')||u.cost))+'<button id="test-lab" type="button">Test and save this year</button><div id="lab-result" role="status">'+(lab.ready&&lab.tests.length?labEvidence(k,lab.tests.at(-1).cost):'')+'</div>'+field(k+'Explain','Compare your tested year with the expected year. Why did the gap between the plans change—or stay the same?')+field(k+'Why','Which plan would you recommend for this person, and why? Use your results and consider the risk of needing more or less care.')+'</div>'}
function labEvidence(k,cost){const u=people[data(k)];return '<h4>Your tested year</h4>'+comparison(u,cost)+'<p>Compared with the expected year, total spending changed by '+money(annual(plans[0],u,cost).total-annual(plans[0],u,u.cost).total)+' for Plan A and '+money(annual(plans[1],u,cost).total-annual(plans[1],u,u.cost).total)+' for Plan B.</p>'}
function content(){switch(state.page){case 0:return '<h2 tabindex="-1">1. Predict one bill</h2><p>Your prediction is not graded for accuracy. What matters is how you use the results to explain your thinking.</p>'+field('name','Name for your report','text')+'<article class="bill"><h3>Fictional medical statement</h3><p>Covered, in-network outpatient procedure<br><strong>Bill amount used in this activity: $5,000</strong></p><p>Deductible: $1,000; already paid: $0.<br>Patient coinsurance: 15%.<br>Out-of-pocket maximum: $10,000; eligible spending already paid: $0. No copay.</p></article>'+field('prediction','How much do you predict the patient will pay ($)?','number')+field('predictWhy','Briefly explain your estimate.')+'<p>Your original prediction will be preserved when you continue.</p>';
case 1:return '<h2 tabindex="-1">2. Follow the bill</h2><p>Calculate the original bill, then test a change that makes the patient pay more and a separate change that makes them pay less. Each test starts from the original plan.</p><div class="card"><h3>Original plan</h3>'+slider('base-d','Deductible',0,10000,100,1000)+slider('base-paid','Deductible already paid',0,1000,50,0)+slider('base-rate','Patient coinsurance',0,100,1,15)+'<p>Out-of-pocket maximum: $10,000. The original settings are fixed so you can compare your prediction fairly.</p><button id="run-bill" type="button">Calculate the original bill</button><div id="bill-result">'+(state.billRun?billSummary(baseline):'')+'</div></div><div id="bill-experiments" '+(!state.billRun?'hidden':'')+'>'+field('billWhy','What surprised you, if anything? Explain the original result using at least two terms: deductible, coinsurance, out-of-pocket maximum.')+experimentHTML('more')+experimentHTML('less')+'</div>';
case 2:return '<h2 tabindex="-1">3. Make an initial plan choice</h2><p>If you did not know how much care you would need next year, which plan would you choose? Explain what makes sense to you. Either choice can be reasonable.</p>'+planTable+'<p class="hint">Premiums are paid even without care. They do not count toward the deductible or out-of-pocket maximum.</p>'+field('initial','Your initial choice','select',opts)+field('initialWhy','Why would you choose this plan?')+'<p>Your initial choice will be preserved.</p>';
case 3:return '<h2 tabindex="-1">4. Choose people and predict</h2><p>Choose one lower-use and one higher-use person. Predict which plan will cost less overall for each expected year before seeing the totals.</p>'+field('low','Lower-use person','select','<option value="">Choose a person</option><option value="A">Person A: rarely uses care</option><option value="D">Person D: concerned about an emergency</option>')+field('high','Higher-use person','select','<option value="">Choose a person</option><option value="B">Person B: regular care</option><option value="C">Person C: planned surgery</option>')+['low','high'].map(k=>data(k)?personIntro(k)+field(k+'Prediction','Which plan do you predict will cost less for this person?','select',opts)+field(k+'PredictWhy','Why do you predict that?'):'').join('')+'<details><summary>Review the two plans</summary>'+planTable+'</details>';
case 4:return labHTML('low');case 5:return labHTML('high');
case 6:return '<h2 tabindex="-1">7. Reconsider your choice</h2><p>Your initial choice: Plan '+esc(data('initial'))+'. '+esc(data('initialWhy'))+'</p>'+field('finalWhy','Would you keep or change your initial choice? Explain using one result from your investigation.')+field('limits','Name one important thing this simulator cannot tell you when choosing real insurance.')+'<p class="hint">A recommendation can consider both expected annual cost and the ability to manage monthly premiums or an unexpected bill.</p>';
case 7:return '<h2 tabindex="-1">8. Review and download</h2><p>Check your saved evidence and responses, then download the PDF to submit in Canvas. Your instructor evaluates your explanations; completion checks only confirm the required work is present.</p><button id="pdf" type="button">Download assignment PDF</button><p id="pdf-status" role="status"></p><div id="report">'+reportHTML()+'</div><details><summary>Optional: explore your own plan privately</summary><p>Use the practice explorer for personal exploration. Its inputs are separate and are never included in this report. Do not enter identifying medical information.</p><a href="/health-insurance/" target="_blank" rel="noopener">Open the practice explorer</a></details>';}}
const labels=['Predict','Follow bill','Choose plan','Predict people','Explore person 1','Explore person 2','Reconsider','PDF'];
function nav(){document.querySelectorAll('[data-step]').forEach((b,i)=>{b.disabled=i>state.done;b.setAttribute('aria-current',i===state.page?'step':'false');b.textContent=(i+1)+'. '+labels[i]+(i>state.done?' (locked)':'')});$('progress').textContent='Section '+(state.page+1)+' of 8. '+state.done+' of 7 work sections complete.'}
function invalidate(){state.done=Math.min(state.done,state.page);nav();save()}
function draw(){nav();$('content').innerHTML=content();$('error').textContent='';$('back').hidden=state.page===0;$('next').hidden=state.page===7;document.querySelectorAll('[data-field]').forEach(e=>{e.value=data(e.id)||(e.id.endsWith('Factor')?'d':'');if((state.page===0&&state.done>0&&e.id!=='name')||(state.page===2&&state.done>2)||(state.page===3&&state.done>3))e.disabled=true;e.oninput=()=>{state.fields[e.id]=e.value;if(e.id==='low'||e.id==='high'){state.fields[e.id+'Prediction']='';state.fields[e.id+'PredictWhy']='';state.labs[e.id]={run:false,tests:[]};invalidate();draw();$(e.id).focus();return}if(e.id.endsWith('Factor')){const k=e.id.replace('Factor','');state.fields[k+'Value']=String(baseline[e.value]);state.ready[k]=false;state.fields[k+'Why']='';invalidate();draw();$(e.id).focus();return}if(e.id==='morePredict'||e.id==='lessPredict'){const k=e.id.replace('Predict','');state.ready[k]=false;state.fields[k+'Why']='';$(k+'-result').innerHTML='';$(k+'Why').value=''}if(e.id.endsWith('TestPredict')){const k=e.id.replace('TestPredict','');state.labs[k].ready=false;state.fields[k+'Explain']='';state.fields[k+'Why']='';$('lab-result').innerHTML='';$(k+'Explain').value='';$(k+'Why').value=''}invalidate()}});
if(state.page===1){['base-d','base-paid','base-rate'].forEach(id=>{$(id).disabled=true;$(id+'-number').disabled=true});$('run-bill').onclick=()=>{state.billRun=true;save();draw();$('bill-result').scrollIntoView({block:'nearest'})};['more','less'].forEach(k=>{let n=Number(data(k+'Value')||baseline[data(k+'Factor')||'d']);bindSlider(k+'-setting',v=>{n=v;state.fields[k+'Value']=v===null?'':String(v);state.ready[k]=false;state.fields[k+'Why']='';$(k+'Why').value='';$(k+'-result').innerHTML='Settings changed. Test and save this value.';invalidate()});$('test-'+k).onclick=()=>{if(!data(k+'Predict').trim()){error('Predict the effect before testing this change.');$(k+'Predict').focus();return}if(n===null){error('Enter a valid setting.');return}const t={factor:data(k+'Factor')||'d',value:n,prediction:data(k+'Predict')};state.attempts[k].push(t);state.ready[k]=true;$(k+'-result').innerHTML=attemptHTML(t);const diff=bill(settingsFor(t)).total-bill(baseline).total;if((k==='more'&&diff<=0)||(k==='less'&&diff>=0))$(k+'-result').insertAdjacentHTML('beforeend','<p>Try another value to make the payment '+k+'.</p>');invalidate()}})}
if(state.page===4||state.page===5){const k=state.page===4?'low':'high',lab=state.labs[k],u=people[data(k)];$('run-lab').onclick=()=>{lab.run=true;save();draw()};let n=Number(data(k+'Cost')||u.cost);bindSlider('medical-cost',v=>{n=v;state.fields[k+'Cost']=v===null?'':String(v);lab.ready=false;state.fields[k+'Explain']='';state.fields[k+'Why']='';$(k+'Explain').value='';$(k+'Why').value='';$('lab-result').innerHTML='Expenses changed. Test and save this year.';invalidate()});$('test-lab').onclick=()=>{if(!data(k+'TestPredict').trim()){error('Predict the effect before testing.');$(k+'TestPredict').focus();return}if(n===null||n===u.cost){error('Choose a valid expense amount different from the expected year.');return}lab.tests.push({cost:n,prediction:data(k+'TestPredict')});lab.ready=true;$('lab-result').innerHTML=labEvidence(k,n);invalidate()}}
if(state.page===7)$('pdf').onclick=downloadPDF;}
function error(s){$('error').textContent=s;$('error').focus()}
function check(p){const req=[['name','prediction','predictWhy'],['billWhy','morePredict','moreWhy','lessPredict','lessWhy'],['initial','initialWhy'],['low','high','lowPrediction','lowPredictWhy','highPrediction','highPredictWhy'],['lowTestPredict','lowExplain','lowWhy'],['highTestPredict','highExplain','highWhy'],['finalWhy','limits']][p];for(const id of req){if(!data(id).trim()){error('Complete: '+(document.querySelector('label[for="'+id+'"]')?.textContent||id));$(id)?.focus();return false}}
if(p===0&&(!Number.isFinite(Number(data('prediction')))||Number(data('prediction'))<0||Number(data('prediction'))>5000)){error('Enter a prediction from $0 to $5,000.');return false}
if(p===1){if(!state.billRun){error('Calculate the original bill first.');return false}for(const k of ['more','less']){const t=state.attempts[k].at(-1),diff=t?bill(settingsFor(t)).total-bill(baseline).total:0;if(!t||!state.ready[k]||(k==='more'?diff<=0:diff>=0)){error('Test and save a change that makes the patient pay '+k+'.');return false}}}
if(p===4||p===5){const k=p===4?'low':'high';if(!state.labs[k].run||!state.labs[k].ready||!state.labs[k].tests.length){error('Calculate the expected year and save a different test year first.');return false}}return true}
function go(p){if(p>state.done)return;state.page=p;draw();$('content').querySelector('h2').focus();save()}
$('next').onclick=()=>{if(check(state.page)){state.done=Math.max(state.done,state.page+1);go(state.page+1)}};$('back').onclick=()=>go(state.page-1);document.querySelectorAll('[data-step]').forEach((b,i)=>b.onclick=()=>go(i));
function download(body,name,type){const url=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('backup').onclick=()=>download(JSON.stringify(state,null,2),'health-insurance-work.json','application/json');
$('restore').onchange=async e=>{try{const v=JSON.parse(await e.target.files[0].text());if(!valid(v))throw Error();state=v;state.page=0;state.done=0;save();draw();$('save-status').textContent='Backup restored. Your saved evidence is kept; continue through the sections to check it.'}catch{error('This is not a valid backup for the revised assignment. Your current work was kept.')}};
function reportHTML(){return '<h3>'+esc(data('name'))+'</h3><h3>Original bill prediction</h3><p>'+money(Number(data('prediction')))+': '+esc(data('predictWhy'))+'</p><h3>Follow the bill</h3>'+billSummary(baseline)+'<p>'+esc(data('billWhy'))+'</p>'+['more','less'].map(k=>'<h4>Pay '+k+'</h4><p>Prediction: '+esc(data(k+'Predict'))+'</p>'+state.attempts[k].map(t=>'<p>Test prediction: '+esc(t.prediction)+'</p>'+attemptHTML(t)).join('')+'<p>Explanation: '+esc(data(k+'Why'))+'</p>').join('')+'<h3>Initial plan choice</h3>'+planTable+'<p>Plan '+esc(data('initial'))+': '+esc(data('initialWhy'))+'</p>'+['low','high'].map(k=>personIntro(k)+'<p>Prediction: Plan '+esc(data(k+'Prediction'))+'. '+esc(data(k+'PredictWhy'))+'</p>'+comparison(people[data(k)],people[data(k)].cost)+'<p>Experiment prediction: '+esc(data(k+'TestPredict'))+'</p>'+state.labs[k].tests.map(t=>'<p>Test prediction: '+esc(t.prediction)+'</p>'+labEvidence(k,t.cost)).join('')+'<p>Explanation: '+esc(data(k+'Explain'))+'</p><p>Recommendation: '+esc(data(k+'Why'))+'</p>').join('')+'<h3>Reconsidered choice</h3><p>'+esc(data('finalWhy'))+'</p><h3>Model limitation</h3><p>'+esc(data('limits'))+'</p>'}
function downloadPDF(){if(!window.jspdf){$('pdf-status').textContent='Reload to load the PDF library. Your saved work is kept.';return}const doc=new window.jspdf.jsPDF({unit:'pt',format:'letter'});let y=60;
function page(){doc.addPage();y=60}function text(s,bold=false){doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(bold?12:10);const lines=doc.splitTextToSize(String(s).normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[–—]/g,'-'),524);for(const line of lines){if(y>727)page();doc.text(line,44,y);y+=14}y+=7}
function row(label,a,b){if(y>720)page();doc.setDrawColor(210);doc.line(44,y+5,568,y+5);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text(label,44,y);doc.text(a,365,y);if(b!=null)doc.text(b,465,y);y+=22}
function billRows(s){const b=bill(s);row('Deductible / already paid',money(s.d),money(s.paid));row('Coinsurance / maximum',s.rate+'%',money(s.max));row('Deductible / coinsurance payment',money(b.ded),money(b.co));row('Patient pays / insurance pays',money(b.total),money(b.insurer))}
function annualRows(u,cost){if(y+200>727)page();const a=plans.map(p=>annual(p,u,cost));row('Annual spending','Plan A','Plan B');[['Premiums','premium'],['Copays','copay'],['Deductible payment','ded'],['Coinsurance payment','co'],['Covered-care spending','care'],['Total premiums + care','total']].forEach(([l,k])=>row(l,money(a[0][k]),money(a[1][k])));text(winner(u,cost))}
text('HEALTH INSURANCE INVESTIGATION',true);text(data('name')+' | HES100 | Fictional 2027 plans');text('1. ORIGINAL BILL PREDICTION',true);text('Fixed covered bill: $5,000. Predicted patient payment: '+money(Number(data('prediction'))));text(data('predictWhy'));text('2. FOLLOW THE BILL: ORIGINAL',true);billRows(baseline);text(data('billWhy'));
['more','less'].forEach(k=>{if(y+210>727)page();text('EXPERIMENT: PAY '+k.toUpperCase(),true);text('Prediction: '+data(k+'Predict'));state.attempts[k].forEach(t=>{if(y+175>727)page();text('Test prediction: '+t.prediction);text('Changed '+factors[t.factor].label+': '+baseline[t.factor]+' to '+t.value+(t.factor==='rate'?'%':''));billRows(settingsFor(t));text('Change in patient payment: '+money(bill(settingsFor(t)).total-bill(baseline).total))});text('Explanation: '+data(k+'Why'))});
page();text('3. INITIAL PLAN CHOICE',true);row('Plan detail','Plan A','Plan B');planRows.forEach(x=>row(x[0],money(x[1]),money(x[2])));row('Patient coinsurance','20%','15%');text('Initial choice: Plan '+data('initial'));text(data('initialWhy'));
['low','high'].forEach(k=>{const u=people[data(k)];page();text(u.name.toUpperCase(),true);text(u.story);text(u.pc+' primary visits; '+u.sp+' specialist visits.');text('Original prediction: Plan '+data(k+'Prediction'));text(data(k+'PredictWhy'));text('EXPECTED YEAR: '+money(u.cost)+' other expenses',true);annualRows(u,u.cost);text('Experiment prediction: '+data(k+'TestPredict'));state.labs[k].tests.forEach(t=>{text('Test prediction: '+t.prediction);text('TEST YEAR: '+money(t.cost)+' other expenses',true);annualRows(u,t.cost);text('Total change from expected: Plan A '+money(annual(plans[0],u,t.cost).total-annual(plans[0],u,u.cost).total)+'; Plan B '+money(annual(plans[1],u,t.cost).total-annual(plans[1],u,u.cost).total))});text('Explanation: '+data(k+'Explain'));text('Recommendation: '+data(k+'Why'))});
text('RECONSIDERED CHOICE',true);text(data('finalWhy'));text('STUDENT-IDENTIFIED LIMITATION',true);text(data('limits'));if(y+140>727)page();text('MODEL AND SOURCES',true);text('Fictional allowed costs, not real prices. Covered in-network care only. Bill tests start from the original plan; prior eligible spending consists of deductible payments. Annual visit copays count toward the maximum, not the deductible; visits are processed first. Other expenses use deductible then coinsurance. Premiums are separate. Networks, exclusions, drug benefits, subsidies and family rules are not modeled.');text('HealthCare.gov: healthcare.gov/glossary/deductible/; healthcare.gov/glossary/co-insurance/; healthcare.gov/glossary/out-of-pocket-maximum-limit/');const count=doc.getNumberOfPages();for(let i=1;i<=count;i++){doc.setPage(i);doc.setFontSize(9);doc.setTextColor(80);doc.text('HES100 | Health insurance evidence',44,30);doc.text(i+' / '+count,520,765)}doc.save('health-insurance-assignment.pdf');$('pdf-status').textContent='PDF downloaded. Check it, then submit it in Canvas.'}
draw();save();
